version: '2.1'

services:

  wordpress:
    build: 
      context: .
      args:
        WORDPRESS_DB_PASSWORD: pass
        PHP_IMAGE_TAG: $PHP_IMAGE_TAG
        WORDPRESS_VERSION: $WORDPRESS_VERSION
    ports:
      - 8080:80
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: healthcheck/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: pass